# Generated by Django 4.1.12 on 2023-11-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Niski'), (1, 'Średni'), (2, 'Wysoki')])),
                ('status', models.IntegerField(choices=[(0, 'Nowe'), (1, 'W trakcie'), (2, 'Zakończone')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issue.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issue.department')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('sex', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issue.position')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issue.issue')),
            ],
            options={
                'db_table': 'issue_log',
            },
        ),
    ]
