# Generated by Django 4.1.12 on 2023-10-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('sex', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issue.position')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
    ]
