# Generated by Django 4.1.12 on 2023-11-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_person_owner_person_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname'], 'permissions': [('can_view_other_persons', 'Pozwala wyświetlać obiekty Person, których użytkownik nie jest właścicielem')]},
        ),
    ]
