# Generated by Django 4.1.12 on 2023-12-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_issuelog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuelog',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='issue.department'),
            preserve_default=False,
        ),
    ]
