# Generated by Django 4.1.12 on 2023-12-03 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0004_alter_issuelog_options_category_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performer', to=settings.AUTH_USER_MODEL),
        ),
    ]
